Milestone 1
tomdan-ai/Hello-Microverse pull request #1
Opened 2023-02-14 20:18 UTC by tomdan-ai

### **On this pull request the following requirements were made:**

- [ ] I set up linter configurations.
- [ ] I ignored node modules.
- [ ] I created HTML with an h1 tag: Hello microverse.
- [ ] I styled the heading with CSS.
- [ ] I edited the README.md file.

2023-02-14 20:41 UTC, Gambit142 requested changes
Hi @tomdan-ai 👋, 

Good job so far! You did well for your first project 👏 

## Highlights
- All linters checks passed ✔️ 
- `node_modules` and the `test.md` file were git ignored ✔️ 
- Good commit messages ✔️ 
- Descriptive pull request summary ✔️ 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-02-14 20:41 UTC, Gambit142 commented on README.md
- [ ] Kindly include 1-3 features of this project in the **_Key Features_** section of your README.md file. You can include learning how to setup linters, learning how to git ignore files and so on. 👍

2023-02-14 20:41 UTC, Gambit142 commented on README.md
- [ ] Kindly include 1-3 features that can be implemented in the **_Future Features_** section. Features like building a webpage, navigation or whatever you desire. 👍

2023-02-14 20:41 UTC, Gambit142 commented on README.md
- [ ] In your MIT.md file, kindly replace the placeholder `[YOUR NAME]` with your name and every occurrence of `[APP TYPE]` with the name of your application. This makes your LICENSE personalized and defined 😎 👍

2023-02-15 08:03 UTC, Lizdev-05 approved these changes
Hi @tomdan-ai, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media1.giphy.com/media/8UF0EXzsc0Ckg/giphy.gif"/>
## Highlights

- [ ] All linters checks passed ✔️
- [ ] node_modules and the test.md file was git ignored ✔️
- [ ] Good commit messages ✔️
- [ ] Descriptive pull request summary ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 08:12 UTC, merged